/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { event_log$_T } from './event_log$_b.js'
export interface event_log_ctx_I {
	event_log$?:event_log$_T
}
