/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import { _b } from '@ctx-core/object'
import type { event_log_Ctx } from './event_log_Ctx'
import type { event_log$_T } from './event_log$_b'
import { event_log$_b } from './event_log$_b'
export interface event_log_ctx_I {
	event_log$?:event_log$_T
	event_log_b_h?:event_log_b_h_T
}
export interface event_log_b_h_T {
	get event_log$():event_log$_T
}
export function event_log_b_h_b(ctx:event_log_Ctx):event_log_b_h_T {
	return _b<event_log_Ctx, 'event_log_b_h'>('event_log_b_h', ()=>{
		return {
			get event_log$() { return event_log$_b(ctx) }
		}
	})(ctx)
}